interface Paths {
  [key: string]: string;
}
export default {
  HOME: "/",
  LOGIN: "/giris-yap",
  REGISTER: "/kayit-ol",
  REGISTER_FORM: "/kayit-formu",
  PROFILE: "/profil",
  TRAIN: "/antreman",
  MATCH: "/mac",
  LESSON: "/ders",
  CALENDAR: "/takvim",
  REQUESTS: "/davetler",
  MATCH_INVITE: "/mac-davet",
  TRAIN_INVITE: "/antreman-davet",
  LESSON_INVITE: "/ders-davet",
  COURT_BOOKING_INVITE: "/kort-kiralama",
  CLUB_COURTS: "/kulup-kortlar",
  STUDENTS: "/egitmen-ogrenciler",
  EXPLORE: "/kesfet",
  EXPLORE_PROFILE: "/profil/",
  CLUB_SUBSCRIPTIONS: "/kulup-uyelikler",
  CLUB_STAFF: "/kulup-personel",
  PAYMENTS: "/odemeler",
  PERFORMANCE: "/performans",
  PLAYERS_LEADERBOARD: "/oyuncu-liderlik-tablosu",
  SOCIAL: "/favoriler-ve-baglantilar",
  NOT_FOUND: "*",
  PLAYER_SUBSCRIPTIONS: "/oyuncu-uyelikler",
  PLAYER_GROUPS: "/oyuncu-gruplar",
  FAVOURITES: "/favoriler",
  MESSAGES: "/mesajlar",
  CLUB_TOURNAMENTS: "/kulup-turnuvalar",
  PLAYER_TOURNAMENTS: "/oyuncu-turnuvalar",
  TOURNAMENT: "/turnuva/",
  CLUB_TOURNAMENT_FIXTURE: "/kulup-turnuva-fikstur/",
} as Paths;
